# Generated by Django 4.2.7 on 2024-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0003_typetravaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('duree', models.FloatField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TypeTravaux',
            new_name='Travaux',
        ),
    ]
