# Generated by Django 4.2.7 on 2024-05-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0004_typemaison_rename_typetravaux_travaux'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMaison',
            new_name='Maison',
        ),
    ]
