# Generated by Django 4.2.7 on 2024-05-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0005_rename_typemaison_maison'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisonTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppConstruction.maison')),
                ('travaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppConstruction.travaux')),
            ],
        ),
    ]
