# Generated by Django 4.2.7 on 2024-05-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0006_maisontravaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
                ('pourcentage', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='maison',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='duree',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='prix',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='maisontravaux',
            name='maison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.maison'),
        ),
        migrations.AlterField(
            model_name='maisontravaux',
            name='quantite',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='maisontravaux',
            name='travaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.travaux'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='prix_unitaire',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='unite',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_finition', models.FloatField(null=True)),
                ('prix_total', models.FloatField(null=True)),
                ('date_devis', models.DateField(null=True)),
                ('date_debut_construction', models.DateField(null=True)),
                ('date_fin_construction', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.client')),
                ('finition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.finition')),
                ('maison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.maison')),
            ],
        ),
    ]
