# Generated by Django 4.2.7 on 2024-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0007_finition_alter_maison_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maison_id', models.BigIntegerField(blank=True, null=True)),
                ('somme', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prix_maison',
                'managed': False,
            },
        ),
    ]
