# Generated by Django 4.2.7 on 2024-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0009_detaildevis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailDevisView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maison_id', models.BigIntegerField(blank=True, null=True)),
                ('travaux_id', models.BigIntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('unite', models.CharField(blank=True, max_length=5, null=True)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('prix_unitaire', models.FloatField(blank=True, null=True)),
                ('prix_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_devis_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='detaildevis',
            name='quantite',
            field=models.FloatField(null=True),
        ),
    ]
