# Generated by Django 4.2.7 on 2024-05-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0010_detaildevisview_detaildevis_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.FloatField()),
                ('devis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppConstruction.devis')),
            ],
        ),
    ]
