# Generated by Django 4.2.7 on 2024-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0011_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='surface',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='duree',
            field=models.FloatField(null=True),
        ),
    ]
