# Generated by Django 4.2.7 on 2024-05-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0012_maison_surface_travaux_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travaux',
            name='duree',
        ),
    ]
