# Generated by Django 4.2.7 on 2024-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0013_remove_travaux_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='travaux',
            name='code_travaux',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
