# Generated by Django 4.2.7 on 2024-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0014_travaux_code_travaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lieu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='ref_devis',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
