# Generated by Django 4.2.7 on 2024-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConstruction', '0015_devis_lieu_devis_ref_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='ref_paiement',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
